import type { CompanionDef, EnemyDef, ItemDef, LocationDef, Skill, CompanionId, LocationId } from './types'

// ===== PLAYER SKILLS =====
export const PLAYER_SKILLS: Skill[] = [
  {
    id: 'heir_slash',
    name: '継承斬り',
    desc: '勇者の血が宿る一撃。敵1体に強力なダメージ。',
    mpCost: 10,
    target: 'enemy_one',
    effect: 'damage',
    power: 2.2,
  },
  {
    id: 'inspire',
    name: '鼓舞',
    desc: '味方全体の攻撃力を1ターン上昇させる。',
    mpCost: 8,
    target: 'ally_all',
    effect: 'atk_up',
    power: 1,
  },
  {
    id: 'guardian_light',
    name: '守護の光',
    desc: '味方1体のHPを40回復する。',
    mpCost: 10,
    target: 'ally_one',
    effect: 'heal',
    power: 40,
  },
  {
    id: 'seal_release',
    name: '封印解放',
    desc: '封印石の力を解放。魔王戦で絶大なダメージ。',
    mpCost: 20,
    target: 'enemy_one',
    effect: 'boss_bonus',
    power: 3.5,
  },
]

// ===== COMPANIONS =====
export const COMPANIONS: Record<CompanionId, CompanionDef> = {
  gordon: {
    id: 'gordon',
    name: 'ゴードン',
    cls: '重騎士',
    emoji: '🛡️',
    desc: '王国騎士団の古参兵。鉄壁の守りで仲間を守る。',
    joinLocId: 'royal_city',
    joinText: '「旅の者よ、私は元王国騎士のゴードンだ。封印石の探索なら力を貸そう。一人では危険すぎる。」',
    baseHp: 120,
    baseMp: 20,
    baseAtk: 14,
    baseDef: 18,
    baseSpd: 6,
    joinLevel: 2,
    skills: [
      { id: 'shield_bash', name: '盾撃', desc: '盾で敵を殴りスタンさせる。', mpCost: 6, target: 'enemy_one', effect: 'stun', power: 1.2 },
      { id: 'iron_wall', name: '鉄壁', desc: '自分の防御力を大幅に上昇させる。', mpCost: 8, target: 'self', effect: 'def_up', power: 1 },
    ],
  },
  liria: {
    id: 'liria',
    name: 'リリア',
    cls: '魔法使い',
    emoji: '🔮',
    desc: '炎の研究をする魔法使い。高い魔力で敵を薙ぎ払う。',
    joinLocId: 'volca_town',
    joinText: '「あなたが封印石を探しているの？面白いわ。私も同行させてもらう。炎の封印石の場所は知っている。」',
    baseHp: 60,
    baseMp: 80,
    baseAtk: 22,
    baseDef: 6,
    baseSpd: 12,
    joinLevel: 3,
    skills: [
      { id: 'fireball', name: '炎球', desc: '炎の球を放ち敵全体を焼き払う。', mpCost: 12, target: 'enemy_all', effect: 'damage', power: 1.4 },
      { id: 'thunder', name: '雷撃', desc: '雷を一点集中。敵1体に大ダメージ。', mpCost: 10, target: 'enemy_one', effect: 'damage', power: 2.5 },
    ],
  },
  sera: {
    id: 'sera',
    name: 'セラ',
    cls: '聖女',
    emoji: '✨',
    desc: '森の神殿に仕える聖女。癒しの力が仲間を救う。',
    joinLocId: 'elda_village',
    joinText: '「旅人様、神殿の力を借りたいですか？私もお供します。封印石を守ることが使命ですから。」',
    baseHp: 70,
    baseMp: 90,
    baseAtk: 10,
    baseDef: 10,
    baseSpd: 9,
    joinLevel: 2,
    skills: [
      { id: 'heal', name: '癒し', desc: '味方1体のHPを50回復する。', mpCost: 6, target: 'ally_one', effect: 'heal', power: 50 },
      { id: 'holy_light', name: '聖なる光', desc: '味方全体のHPを25回復し状態異常を癒す。', mpCost: 14, target: 'ally_all', effect: 'heal', power: 25 },
    ],
  },
  dan: {
    id: 'dan',
    name: 'ダン',
    cls: '盗賊',
    emoji: '🗡️',
    desc: '港町に潜む元盗賊。罠を見破り影から攻撃する。',
    joinLocId: 'marina_port',
    joinText: '「ちぇ、仕方ねぇな。借りがあるから付き合ってやる。ただし俺のやり方で動かせてもらうぜ。」',
    baseHp: 75,
    baseMp: 40,
    baseAtk: 18,
    baseDef: 8,
    baseSpd: 16,
    joinLevel: 3,
    skills: [
      { id: 'poison_blade', name: '毒刃', desc: '毒を塗った刃で攻撃。敵1体に毒を付与。', mpCost: 5, target: 'enemy_one', effect: 'poison', power: 1.0 },
      { id: 'shadow_strike', name: '影走り', desc: '闇に紛れた奇襲。敵1体に高速で2連撃。', mpCost: 8, target: 'enemy_one', effect: 'damage', power: 1.8 },
    ],
  },
  flare: {
    id: 'flare',
    name: 'フレア',
    cls: '弓使い',
    emoji: '🏹',
    desc: '炎の街で傭兵をしていた弓の名手。遠距離から正確に射る。',
    joinLocId: 'volca_town',
    joinText: '「封印石を探す旅か。報酬はいらない。魔王が復活したら私の故郷が滅ぶ。それだけで十分だ。」',
    baseHp: 80,
    baseMp: 30,
    baseAtk: 16,
    baseDef: 9,
    baseSpd: 14,
    joinLevel: 3,
    skills: [
      { id: 'rapid_shot', name: '連射', desc: '敵1体に矢を3本連続で射る。', mpCost: 8, target: 'enemy_one', effect: 'damage', power: 1.9 },
      { id: 'flame_arrow', name: '炎矢', desc: '炎をまとった矢で敵全体を攻撃。', mpCost: 12, target: 'enemy_all', effect: 'damage', power: 1.3 },
    ],
  },
  kain: {
    id: 'kain',
    name: 'カイン',
    cls: '狂戦士',
    emoji: '⚔️',
    desc: '炎山に一人で住む孤高の戦士。制御不能の力を秘める。',
    joinLocId: 'ignis_dungeon',
    joinText: '「お前ら、俺を倒してみせたか。認めてやる。一緒に行ってやる。ただし邪魔はするな。」',
    baseHp: 110,
    baseMp: 20,
    baseAtk: 26,
    baseDef: 8,
    baseSpd: 10,
    joinLevel: 4,
    skills: [
      { id: 'berserk_slash', name: '狂乱斬り', desc: '自分のHPも消費する狂気の一撃。', mpCost: 6, target: 'enemy_one', effect: 'damage', power: 3.0 },
      { id: 'war_cry', name: '雄叫び', desc: '戦場を震わす叫び。敵の攻撃力を下げる。', mpCost: 8, target: 'enemy_all', effect: 'debuff_atk', power: 1 },
    ],
  },
  win: {
    id: 'win',
    name: 'ウィン',
    cls: '風術師',
    emoji: '🌪️',
    desc: '港町で商船を守る風の術師。状態異常を操る。',
    joinLocId: 'marina_port',
    joinText: '「封印石を集める旅？嵐の封印石の場所なら知っています。私の風が案内しましょう。」',
    baseHp: 65,
    baseMp: 85,
    baseAtk: 14,
    baseDef: 9,
    baseSpd: 13,
    joinLevel: 3,
    skills: [
      { id: 'tornado', name: '竜巻', desc: '小さな竜巻で敵全体にダメージ。', mpCost: 11, target: 'enemy_all', effect: 'damage', power: 1.2 },
      { id: 'wind_shield', name: '風壁', desc: '風の壁を作り味方全体の防御力を上昇させる。', mpCost: 9, target: 'ally_all', effect: 'def_up', power: 1 },
    ],
  },
  march: {
    id: 'march',
    name: 'マーチ',
    cls: '商人',
    emoji: '💰',
    desc: '廃都で細々と商売をする商人。戦いは苦手だがサポートは一流。',
    joinLocId: 'rune_city',
    joinText: '「売れるものなら何でも売りますよ。でも今は商売より世界の平和が先ですかな。同行します。」',
    baseHp: 70,
    baseMp: 50,
    baseAtk: 12,
    baseDef: 12,
    baseSpd: 10,
    joinLevel: 3,
    skills: [
      { id: 'gold_shield', name: '金の盾', desc: '金貨を盾にして味方1体を守る。防御力大幅上昇。', mpCost: 7, target: 'ally_one', effect: 'def_up', power: 2 },
      { id: 'emergency_supply', name: '緊急調達', desc: '持ち物からアイテムを取り出し味方全体のHPを回復。', mpCost: 10, target: 'ally_all', effect: 'heal', power: 30 },
    ],
  },
  belk: {
    id: 'belk',
    name: 'ベルク',
    cls: '獣戦士',
    emoji: '🐺',
    desc: '廃都に潜む巨漢の獣戦士。獣の咆哮で敵を威圧する。',
    joinLocId: 'rune_city',
    joinText: '「ガアアア！…あ、すまん。つい。お前らはちゃんと戦えるな。仲間に入れてくれるか？」',
    baseHp: 115,
    baseMp: 25,
    baseAtk: 24,
    baseDef: 14,
    baseSpd: 8,
    joinLevel: 4,
    skills: [
      { id: 'roar', name: '野獣の咆哮', desc: '恐ろしい咆哮で敵全体の攻撃力を下げる。', mpCost: 7, target: 'enemy_all', effect: 'debuff_atk', power: 1 },
      { id: 'earth_crush', name: '大地砕き', desc: '大地を叩き割る超重量撃。敵1体に大ダメージ。', mpCost: 12, target: 'enemy_one', effect: 'damage', power: 2.8 },
    ],
  },
  noel: {
    id: 'noel',
    name: 'ノール',
    cls: '聖騎士',
    emoji: '⚡',
    desc: '霧の里を守る聖騎士。攻守のバランスが最も高い。',
    joinLocId: 'mist_village',
    joinText: '「封印石の力を取り戻す旅か。私も協力しよう。この地に封印された光の力を君に貸そう。」',
    baseHp: 100,
    baseMp: 55,
    baseAtk: 20,
    baseDef: 16,
    baseSpd: 11,
    joinLevel: 5,
    skills: [
      { id: 'holy_strike', name: '聖撃', desc: '光の力で敵1体に聖属性ダメージ。', mpCost: 10, target: 'enemy_one', effect: 'damage', power: 2.0 },
      { id: 'guardian_aura', name: '守護の光輪', desc: '光の輪を展開し味方全体の防御力と攻撃力を上昇。', mpCost: 14, target: 'ally_all', effect: 'atk_up', power: 1 },
    ],
  },
  ain: {
    id: 'ain',
    name: 'アイン',
    cls: '錬金術師',
    emoji: '⚗️',
    desc: '霧の里に隠れ住む錬金術師。爆薬と薬の扱いに長ける。',
    joinLocId: 'mist_village',
    joinText: '「実験体として……じゃなくて、仲間として私を連れて行く？喜んで！最新の爆薬を試させてもらうわ。」',
    baseHp: 68,
    baseMp: 75,
    baseAtk: 16,
    baseDef: 10,
    baseSpd: 11,
    joinLevel: 5,
    skills: [
      { id: 'bomb_throw', name: '爆薬投擲', desc: '強力な爆薬を敵全体に投げつける。', mpCost: 12, target: 'enemy_all', effect: 'damage', power: 1.6 },
      { id: 'power_drug', name: '強化薬', desc: '特製薬で味方1体の攻撃力を大幅に上昇させる。', mpCost: 9, target: 'ally_one', effect: 'atk_up', power: 2 },
    ],
  },
  sofia: {
    id: 'sofia',
    name: 'ソフィア',
    cls: '幻術師',
    emoji: '🌙',
    desc: '暗黒の森に囚われていた幻術師。闇の幻惑で敵を操る。',
    joinLocId: 'shadowgrave',
    joinText: '「助けてくれてありがとう。暗黒の森の封印石……私は知っている。案内させて。必ず力になる。」',
    baseHp: 65,
    baseMp: 95,
    baseAtk: 18,
    baseDef: 7,
    baseSpd: 15,
    joinLevel: 5,
    skills: [
      { id: 'illusion', name: '幻惑', desc: '幻を見せて敵全体の攻撃力を大幅に下げる。', mpCost: 10, target: 'enemy_all', effect: 'debuff_atk', power: 2 },
      { id: 'mind_break', name: '精神崩壊', desc: '精神に直接干渉し敵1体に大ダメージ＋スタン。', mpCost: 16, target: 'enemy_one', effect: 'stun', power: 1.8 },
    ],
  },
}

// ===== ENEMIES =====
export const ENEMIES: Record<string, EnemyDef> = {
  // 炎エリア
  slime: {
    id: 'slime', name: 'スライム', emoji: '🟢',
    hp: 30, mp: 0, atk: 8, def: 4, spd: 5,
    skills: [], exp: 10, gold: 8,
  },
  goblin: {
    id: 'goblin', name: 'ゴブリン', emoji: '👺',
    hp: 45, mp: 10, atk: 12, def: 6, spd: 9,
    skills: [{ id: 'goblin_stab', name: '突き', desc: '素早い刺突。', mpCost: 4, target: 'enemy_one', effect: 'damage', power: 1.3 }],
    exp: 18, gold: 15,
  },
  fire_goblin: {
    id: 'fire_goblin', name: '炎ゴブリン', emoji: '🔥',
    hp: 55, mp: 20, atk: 15, def: 7, spd: 10,
    skills: [{ id: 'fire_bite', name: '炎噛み', desc: '炎をまとった噛みつき。', mpCost: 8, target: 'enemy_one', effect: 'damage', power: 1.6 }],
    exp: 25, gold: 20,
  },
  volcano_dragon: {
    id: 'volcano_dragon', name: '炎竜ヴォルカノス', emoji: '🐉',
    hp: 280, mp: 60, atk: 28, def: 15, spd: 12,
    skills: [
      { id: 'fire_breath', name: '炎のブレス', desc: '全体に炎ダメージ。', mpCost: 15, target: 'enemy_all', effect: 'damage', power: 1.5 },
      { id: 'tail_sweep', name: 'テールスイープ', desc: '尻尾で薙ぎ払う。', mpCost: 8, target: 'enemy_one', effect: 'damage', power: 2.2 },
    ],
    exp: 120, gold: 80, isBoss: true, sealStone: 'fire',
  },
  // 嵐エリア
  ghost: {
    id: 'ghost', name: '亡霊', emoji: '👻',
    hp: 40, mp: 30, atk: 14, def: 3, spd: 13,
    skills: [{ id: 'curse', name: 'たたり', desc: '呪いの力。', mpCost: 8, target: 'enemy_one', effect: 'poison', power: 1.0 }],
    exp: 22, gold: 18,
  },
  storm_bat: {
    id: 'storm_bat', name: '嵐蝙蝠', emoji: '🦇',
    hp: 38, mp: 15, atk: 16, def: 4, spd: 18,
    skills: [{ id: 'sonic_wave', name: '超音波', desc: '音波攻撃でスタン。', mpCost: 7, target: 'enemy_one', effect: 'stun', power: 0.8 }],
    exp: 20, gold: 16,
  },
  thunder_spirit: {
    id: 'thunder_spirit', name: '雷精', emoji: '⚡',
    hp: 60, mp: 50, atk: 18, def: 8, spd: 15,
    skills: [{ id: 'lightning', name: '稲妻', desc: '強力な電撃。', mpCost: 12, target: 'enemy_one', effect: 'damage', power: 2.0 }],
    exp: 30, gold: 22,
  },
  storm_rex: {
    id: 'storm_rex', name: '嵐鬼ストームレックス', emoji: '🌩️',
    hp: 320, mp: 80, atk: 30, def: 12, spd: 16,
    skills: [
      { id: 'storm_blast', name: '嵐の爆風', desc: '全体に嵐ダメージ。', mpCost: 14, target: 'enemy_all', effect: 'damage', power: 1.4 },
      { id: 'lightning_strike', name: '雷撃落とし', desc: '1体に強烈な雷。', mpCost: 10, target: 'enemy_one', effect: 'damage', power: 2.5 },
    ],
    exp: 150, gold: 100, isBoss: true, sealStone: 'storm',
  },
  // 闇エリア
  shadow_person: {
    id: 'shadow_person', name: '影人', emoji: '🌑',
    hp: 50, mp: 25, atk: 18, def: 8, spd: 14,
    skills: [{ id: 'shadow_claw', name: '影爪', desc: '影の爪で切り裂く。', mpCost: 6, target: 'enemy_one', effect: 'damage', power: 1.4 }],
    exp: 28, gold: 24,
  },
  dark_hound: {
    id: 'dark_hound', name: '闇猟犬', emoji: '🐕',
    hp: 65, mp: 10, atk: 20, def: 9, spd: 17,
    skills: [{ id: 'dark_bite', name: '闇噛み', desc: '闇の力を込めた噛みつき。', mpCost: 5, target: 'enemy_one', effect: 'poison', power: 1.2 }],
    exp: 32, gold: 26,
  },
  death_knight: {
    id: 'death_knight', name: '死霊騎士', emoji: '💀',
    hp: 80, mp: 40, atk: 22, def: 14, spd: 9,
    skills: [{ id: 'death_slash', name: '死の一撃', desc: '呪われた剣で斬る。', mpCost: 10, target: 'enemy_one', effect: 'damage', power: 2.1 }],
    exp: 38, gold: 30,
  },
  shadow_lord: {
    id: 'shadow_lord', name: '暗黒将軍シャドウロード', emoji: '🗡️',
    hp: 360, mp: 70, atk: 32, def: 18, spd: 13,
    skills: [
      { id: 'dark_wave', name: '暗黒波動', desc: '全体に闇ダメージ。', mpCost: 13, target: 'enemy_all', effect: 'damage', power: 1.4 },
      { id: 'curse_blade', name: '呪刃', desc: '毒と大ダメージを与える。', mpCost: 11, target: 'enemy_one', effect: 'poison', power: 2.0 },
    ],
    exp: 180, gold: 120, isBoss: true, sealStone: 'dark',
  },
  // 魔王城
  castle_guard: {
    id: 'castle_guard', name: '魔王の衛兵', emoji: '⚔️',
    hp: 90, mp: 30, atk: 25, def: 16, spd: 10,
    skills: [{ id: 'guard_strike', name: '衛兵の一撃', desc: '重い一撃。', mpCost: 8, target: 'enemy_one', effect: 'damage', power: 1.8 }],
    exp: 40, gold: 35,
  },
  dark_ruler: {
    id: 'dark_ruler', name: '魔王ダークルーラー', emoji: '👑',
    hp: 500, mp: 120, atk: 38, def: 20, spd: 15,
    skills: [
      { id: 'dark_dominion', name: '暗黒支配', desc: '全体に強力な闇ダメージ。', mpCost: 18, target: 'enemy_all', effect: 'damage', power: 1.8 },
      { id: 'soul_crush', name: '魂砕き', desc: '1体の魂を砕く超強撃。', mpCost: 20, target: 'enemy_one', effect: 'damage', power: 3.2 },
      { id: 'dark_curse', name: '魔王の呪い', desc: '全体を毒＋スタン状態にする。', mpCost: 15, target: 'enemy_all', effect: 'poison', power: 1.0 },
    ],
    exp: 500, gold: 300, isBoss: true,
  },
}

// ===== ITEMS =====
export const ITEMS: Record<string, ItemDef> = {
  potion: {
    id: 'potion', name: 'ポーション', emoji: '🧪',
    desc: 'HPを50回復する。', effect: 'heal_hp', power: 50, price: 100,
  },
  hi_potion: {
    id: 'hi_potion', name: 'ハイポーション', emoji: '💊',
    desc: 'HPを120回復する。', effect: 'heal_hp', power: 120, price: 250,
  },
  ether: {
    id: 'ether', name: 'エーテル', emoji: '✨',
    desc: 'MPを30回復する。', effect: 'heal_mp', power: 30, price: 120,
  },
  panacea: {
    id: 'panacea', name: '万能薬', emoji: '🌿',
    desc: 'HPを100、MPを40回復する。', effect: 'heal_both', power: 100, price: 300,
  },
  antidote: {
    id: 'antidote', name: '毒消し', emoji: '🫙',
    desc: '毒・スタン状態を回復する。', effect: 'cure_status', power: 0, price: 80,
  },
}

// ===== LOCATIONS =====
export const LOCATIONS: Record<LocationId, LocationDef> = {
  royal_city: {
    id: 'royal_city', name: '王都リーベル', emoji: '🏰',
    type: 'town',
    desc: '王国の中心。古びた城壁に囲まれた大きな都市。ここから封印石の旅が始まる。',
    connections: ['volca_town', 'elda_village'],
    travelDays: { volca_town: 3, elda_village: 2 },
    companionId: 'gordon',
    shopItems: ['potion', 'ether', 'antidote'],
    hasInn: true,
  },
  volca_town: {
    id: 'volca_town', name: '炎の街ヴォルカ', emoji: '🌋',
    type: 'town',
    desc: '火山の麓に広がる熱い街。炎の術師たちが住む。',
    connections: ['royal_city', 'elda_village', 'ignis_dungeon'],
    travelDays: { royal_city: 3, elda_village: 3, ignis_dungeon: 2 },
    companionId: 'liria',
    shopItems: ['potion', 'ether', 'antidote'],
    hasInn: true,
  },
  elda_village: {
    id: 'elda_village', name: '迷いの森の里エルダ', emoji: '🌲',
    type: 'town',
    desc: '深い森の中に隠れた小さな里。神殿の聖女が住む穏やかな場所。',
    connections: ['royal_city', 'volca_town', 'marina_port'],
    travelDays: { royal_city: 2, volca_town: 3, marina_port: 3 },
    companionId: 'sera',
    shopItems: ['potion', 'hi_potion', 'ether'],
    hasInn: true,
  },
  marina_port: {
    id: 'marina_port', name: '港町マリナ', emoji: '⚓',
    type: 'town',
    desc: '海に面した賑やかな港町。商人や船乗りが行き交う。',
    connections: ['elda_village', 'rune_city', 'stormia_tower'],
    travelDays: { elda_village: 3, rune_city: 3, stormia_tower: 2 },
    companionId: 'dan',
    shopItems: ['potion', 'hi_potion', 'ether', 'panacea'],
    hasInn: true,
  },
  rune_city: {
    id: 'rune_city', name: '廃都ルーン', emoji: '🏚️',
    type: 'town',
    desc: '嵐の被害で廃れた都市。まだ人が住み続けている。',
    connections: ['marina_port', 'mist_village'],
    travelDays: { marina_port: 3, mist_village: 3 },
    companionId: 'march',
    shopItems: ['hi_potion', 'ether', 'panacea', 'antidote'],
    hasInn: true,
  },
  mist_village: {
    id: 'mist_village', name: '霧の里ミスト', emoji: '🌫️',
    type: 'town',
    desc: '濃い霧に包まれた里。闇の力に最も近い場所にある。',
    connections: ['rune_city', 'shadowgrave', 'darkfort'],
    travelDays: { rune_city: 3, shadowgrave: 2, darkfort: 4 },
    companionId: 'noel',
    shopItems: ['hi_potion', 'panacea', 'ether', 'antidote'],
    hasInn: true,
  },
  ignis_dungeon: {
    id: 'ignis_dungeon', name: '炎山イグニス', emoji: '🌋',
    type: 'dungeon',
    desc: '炎の封印石が眠る活火山のダンジョン。高温と炎の罠が行く手を塞ぐ。',
    connections: ['volca_town'],
    travelDays: { volca_town: 2 },
    companionId: 'kain',
    sealStone: 'fire',
    enemyPool: ['slime', 'goblin', 'fire_goblin'],
    bossId: 'volcano_dragon',
  },
  stormia_tower: {
    id: 'stormia_tower', name: '嵐の塔ストーミア', emoji: '🌩️',
    type: 'dungeon',
    desc: '常に嵐が吹き荒れる廃塔。嵐の封印石が最上階に眠る。',
    connections: ['marina_port'],
    travelDays: { marina_port: 2 },
    sealStone: 'storm',
    enemyPool: ['ghost', 'storm_bat', 'thunder_spirit'],
    bossId: 'storm_rex',
  },
  shadowgrave: {
    id: 'shadowgrave', name: '暗黒の森シャドウグレイブ', emoji: '🌑',
    type: 'dungeon',
    desc: '光が届かない深い森。囚われた幻術師ソフィアがいる。',
    connections: ['mist_village'],
    travelDays: { mist_village: 2 },
    companionId: 'sofia',
    sealStone: 'dark',
    enemyPool: ['shadow_person', 'dark_hound', 'death_knight'],
    bossId: 'shadow_lord',
  },
  darkfort: {
    id: 'darkfort', name: '魔王城ダークフォート', emoji: '🏯',
    type: 'castle',
    desc: '封印が解けかけた魔王の城。3つの封印石を持つ者だけが挑める。',
    connections: ['mist_village'],
    travelDays: { mist_village: 4 },
    enemyPool: ['castle_guard'],
    bossId: 'dark_ruler',
    requireAllStones: true,
  },
}

// ===== COMPANION FLARE (second companion at volca_town) =====
// Note: volca_town already has liria. flare joins via event after liria joins.

export function getExpToNext(level: number): number {
  return level * 35
}

export function getDifficultyMultiplier(difficulty: string): { days: number; enemyHpMult: number; playerHpMult: number } {
  switch (difficulty) {
    case 'easy':   return { days: 120, enemyHpMult: 0.7, playerHpMult: 1.3 }
    case 'hard':   return { days: 80,  enemyHpMult: 1.4, playerHpMult: 0.8 }
    default:       return { days: 100, enemyHpMult: 1.0, playerHpMult: 1.0 }
  }
}
